### ISSUE TITLE
Questions regarding QA

### ISSUE THREAD

**Issue by laurentperez** [WICG/ad-click-attribution#13]
Hi

Context : we have a QA team which is responsible for validating various campaign scripts or custom tracking events which are implemented by our developers (analytics, tag manager, gtag, fb pixel, adobe, JS client or server side PHP, the list goes on)

Thanks to web inspector or Chrome or Firefox extensions, the QA process is facilitated.

Concern : currently, tailing and greping the syslog to check for correct Ads parameters is not very good for QA teams, it requires shell experience or sometimes administrative privileges
We would like to use the WebInspector/Devtools for QA, just like we do atm.

Proposal : add a new tab in WebInspector dedicated to Ads debugging
Should I fill a WebKit enhancement request ?

**Comment by johnwilander** [comment]
We considered this and I even embarked on an implementation which grew significantly in size and complexity as I went. The reason is that Web Inspector handles _webpages_, whereas everything that happens beyond the ad click is processed in the networking process.

The ad click conversion does happen on a webpage and debug info could be piped back from the network process to the correct page and further to Web Inspector.

But the final step — the ephemeral, cookieless POST with attribution data — has no webpage context at all. We would either have to introduce some kind of global browser inspection or broadcast the event to all webpages.

All of this is to say, yes, we'd like to support debug output in Web Inspector but it's a larger effort than it may seem.

**Comment by johnwilander** [comment]
I'll close this since it's not a spec issue. Please do file a WebKit issue so that we have concrete feedback on why this is needed.
