### ISSUE TITLE
related work for visibility & other metrics

### ISSUE THREAD

**Issue by michael-oneill** [WICG/ad-click-attribution#2]
Can the web advertising business group get an acknowledgement for related work started in 
January? 
This similarly uses a .well-known path with no cookies, but for advertisement visibility analytics. 
It also addresses fraud detection, which could be an issue with conversion also. Where money could flow as a result of counting transactions, fraud will become an issue.
https://github.com/w3c/web-advertising/blob/master/admetrics.md

**Comment by othermaciej** [comment]
Good thoughts there. We weren't aware of this web advertising business group's work, and would welcome collaboration.

**Comment by michael-oneill** [comment]
Thanks. 
Its hard to understand the lack of awareness though, since one of the authors was a member of the advertising business group taking part in discussions when the work was proposed.
Given that an acknowledgement would simply be courteous.

**Comment by othermaciej** [comment]
We'll gladly acknowledge this as related work. For what it's worth, we've been working on this proposal internally since before the Explainer was published, so there was no direct inspiration here, though perhaps we were both influenced by common sources. But in any case it's a good practice to mention other work in the area.

**Comment by michael-oneill** [comment]
Thanks!
